### ISSUE TITLE
Feature Request : Readonly Mode

### ISSUE THREAD

**Issue by etay-schur-sp** [avim101/am-js-tree#2]
Dear Avim101 ... 
I am very impressed by your flawless work , I am looking forward to use more of your components , BUT ... I have small Feature Request ... 
Can you PLEASE add a "Read Only Mode" , it will make our company life so easier ! 

Thanks alot !

**Comment by avim101** [comment]
Dear etay-schur-sp,
Thanks for getting interested in my component.
However this is only a simple wrapper that helps you integrate jsTree plugin in to your angular controller, so every option that exists in jsTree are available in this wrapper through the configuration object .
I don't really understand what do you mean by "read only mode" but feel free to open PR

**Comment by etay-schur-sp** [comment]
On it !
